Controllers/AbastecimentoController.cs
using BTZ_Transports.Models;
using BTZ_Transports.Repository;
using BTZ_Transports.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTZ_Transports.Controllers
{
	[Authorize]
	public class AbastecimentoController : Controller
	{
		private readonly IAbastecimentoRepository _abastecimentoRepository;
        private readonly ICombustivelRepository _combustivelRepository;
        private readonly IMotoristaRepository _motoristaRepository;
        private readonly IVeiculoRepository _veiculoRepository;

        public AbastecimentoController(IAbastecimentoRepository abastecimentoRepository, 
            ICombustivelRepository combustivelRepository, 
            IMotoristaRepository motoristaRepository, 
            IVeiculoRepository veiculoRepository)
        {
            _abastecimentoRepository = abastecimentoRepository;
            _combustivelRepository = combustivelRepository;
            _motoristaRepository = motoristaRepository;
            _veiculoRepository = veiculoRepository;
        }

        public IActionResult Index()
		{
			var abastecimentos = _abastecimentoRepository.GetAll();
			return View(abastecimentos);
		}

		public IActionResult Create()
		{
            GetListas();
			return View();
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Create(AbastecimentoViewModel viewModel)
		{
			if (ModelState.IsValid && CustomValidationIsValid(viewModel))
			{
				CalculaValorTotalCombustivel(viewModel);

				_abastecimentoRepository.Add(viewModel);
				TempData["MSG_SUCCESS"] = "Abastecimento registrado com sucesso!";

				return RedirectToAction(nameof(Index));
			}

			GetListas(viewModel);
			return View(viewModel);
		}

		private void CalculaValorTotalCombustivel(AbastecimentoViewModel viewModel)
		{
			var combustivel = _combustivelRepository.GetById(viewModel.combustivelId);

			viewModel.ValorTotal = viewModel.QuantidadeAbastecida * combustivel.Preco;
		}

		public IActionResult Details(int id)
		{
			var abastecimento = _abastecimentoRepository.GetById(id);
			GetListas(abastecimento);
			return View(abastecimento);
		}

		private void GetListas(AbastecimentoViewModel viewModel = null)
        {
			GetVeiculos(viewModel?.veiculoId > 0 ? viewModel.veiculoId : null);
			GetMotoristas(viewModel?.motoristaId > 0 ? viewModel.motoristaId : null);
			GetCombustivel(viewModel?.combustivelId > 0 ? viewModel.combustivelId : null);
        }

		private void GetVeiculos(int? id)
		{
			var combustiveis = _veiculoRepository.GetAll();
			var lista = new SelectList(combustiveis, "Id", "NomeVeiculo");

			if (id != null)
			{
				foreach (var item in lista)
				{
					if (int.Parse(item.Value) == id)
					{
						item.Selected = true;
						break;
					}
				}
			}

			ViewBag.ListaVeiculosSelectList = lista;
		}

		private void GetMotoristas(int? id)
		{
			var combustiveis = _motoristaRepository.GetAll();
			var lista = new SelectList(combustiveis, "Id", "Nome");

			if (id != null)
			{
				foreach (var item in lista)
				{
					if (int.Parse(item.Value) == id)
					{
						item.Selected = true;
						break;
					}
				}
			}

			ViewBag.ListaMotoristasSelectList = lista;
		}

		private void GetCombustivel(int? id)
        {
            var combustiveis = _combustivelRepository.GetAll();
            var lista = new SelectList(combustiveis, "Id", "Nome");

            if (id != null)
            {
                foreach (var item in lista)
                {
                    if (int.Parse(item.Value) == id)
                    {
                        item.Selected = true;
                        break;
                    }
                }
            }

            ViewBag.ListaCombustiveisSelectList = lista;
        }

		private bool CustomValidationIsValid(AbastecimentoViewModel viewModel)
		{
			bool ret = true;

			var veiculoDB = _veiculoRepository.GetById(viewModel.veiculoId);

			if (viewModel.QuantidadeAbastecida > veiculoDB.CapacidadeMaximaTanque)
				ModelState.AddModelError("QuantidadeAbastecida", "A quantidade abastecida informada é maior que a capacidade máxima do veiculo selecionado.");

			if (viewModel.combustivelId > veiculoDB.combustivelId)
				ModelState.AddModelError("combustivelId", "O tipo do combustível selecionado é diferente do cadastrado para este veículo.");


			int countErros = ModelState.Values.Count(x => x.Errors.Count > 0);

			if (countErros > 0)
				ret = false;

			return ret;
		}
	}
}

Controllers/MotoristaController.cs
using BTZ_Transports.Repository;
using BTZ_Transports.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BTZ_Transports.Controllers
{
	[Authorize]
	public class MotoristaController : Controller
    {
        private readonly IMotoristaRepository _motoristaRepository;

        public MotoristaController(IMotoristaRepository motoristaRepository)
        {
            _motoristaRepository = motoristaRepository;
        }

        public IActionResult Index()
        {
            return View(_motoristaRepository.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

		[ValidateAntiForgeryToken]
		[HttpPost]
        public IActionResult Create(MotoristaViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                _motoristaRepository.Add(viewModel);

                TempData["MSG_SUCCESS"] = "Motorista criado com sucesso!";
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

		public IActionResult Details(int id)
		{
            var motorista = _motoristaRepository.GetById(id);
			return View(motorista);
		}

		public IActionResult Edit(int id)
		{
			var motorista = _motoristaRepository.GetById(id);
			return View(motorista);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Edit(MotoristaViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				_motoristaRepository.Update(viewModel);
                TempData["MSG_SUCCESS"] = "Motorista atualizado com sucesso!";
                return RedirectToAction(nameof(Index));
			}

			return View(viewModel);
		}

		public IActionResult Delete(int? id)
		{
			if (id == null)
                TempData["MSG_ERRO"] = "Ocorreu um erro ao realizar a exclusão!";
            else
            {
                var status = _motoristaRepository.Delete(id.Value);

                if (!status)
                    TempData["MSG_ERRO"] = "Ocorreu um erro ao realizar a exclusão!";
                else
                    TempData["MSG_SUCCESS"] = "Motorista excluído com sucesso!";
            }
            
            return RedirectToAction(nameof(Index));
        }
	}
}

Controllers/VeiculoController.cs
using BTZ_Transports.Repository;
using BTZ_Transports.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTZ_Transports.Controllers
{
	[Authorize]
	public class VeiculoController : Controller
    {
        private readonly IVeiculoRepository _veiculoRepository;
        private readonly ICombustivelRepository _combustivelRepository;

		public VeiculoController(IVeiculoRepository repository, 
			ICombustivelRepository combustivelRepository)
		{
			_veiculoRepository = repository;
			_combustivelRepository = combustivelRepository;
		}

		public IActionResult Index()
        {
			var veiculos = _veiculoRepository.GetAll();
            return View(veiculos);
        }

		public IActionResult Create()
		{
			GetLista();
			return View();
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Create(VeiculoViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				_veiculoRepository.Add(viewModel);
				TempData["MSG_SUCCESS"] = "Veículo criado com sucesso!";

				return RedirectToAction(nameof(Index));
			}

			GetLista();
			return View(viewModel);
		}

		public IActionResult Details(int id)
		{
            GetLista();
			var veiculo = _veiculoRepository.GetById(id);
            return View(veiculo);
		}

		public IActionResult Edit(int id)
		{
			var veiculo = _veiculoRepository.GetById(id);
			GetLista(veiculo.combustivelId);

			return View(veiculo);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Edit(VeiculoViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				_veiculoRepository.Update(viewModel);
				TempData["MSG_SUCCESS"] = "Veículo atualizado com sucesso!";

				return RedirectToAction(nameof(Index));
			}

			GetLista();
			return View(viewModel);
		}

		public IActionResult Delete(int? id)
		{
			if (id == null)
				TempData["MSG_ERRO"] = "Ocorreu um erro ao realizar a exclusão!";
			else
			{
				var status = _veiculoRepository.Delete(id.Value);

				if (status)
					TempData["MSG_SUCCESS"] = "Veículo excluído com sucesso!";
				else
					TempData["MSG_ERRO"] = "Veículo não encontrado!";
			}

			return RedirectToAction(nameof(Index));
		}

		private void GetLista(int? id = null)
        {
			var combustiveis = _combustivelRepository.GetAll();
			var lista = new SelectList(combustiveis, "Id", "Nome");

			if (id  != null)
			{
				foreach (var item in lista)
				{
					if (int.Parse(item.Value )== id)
					{
						item.Selected = true;
						break;
					}
				}
			}

			ViewBag.ListaCombustiveisSelectList = lista;
        }
	}
}

Views/Shared/_Delete.cshtml
<div class="modal fade" id="basicModal" tabindex="1" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Atenção</h4>
				<button type="button" class="close" data-bs-dismiss="modal" value="delete" aria-hidden="true">x</button>
			</div>
			<div class="modal-body">
				Tem certeza que deseja apagar este registro?
			</div>
			<div class="modal-footer">
				<button data-bs-dismiss="modal" type="button" class="btn btn-secondary">Cancelar</button>
				<button id="btnContinueToDelete" type="button" value="delete" class="btn btn-danger">Deletar</button>
			</div>
		</div>
	</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BTZ Transports</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body style="background-color: ghostwhite;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/bitzen_logo.png" width="150px" style="margin-top: -5px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" style="font-size: 20px;" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Motorista" asp-action="Index">Motorista</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Veiculo" asp-action="Index">Veículo</a>
                                </li>
                                <li >
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Abastecimento" asp-action="Index">Abastecimento</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificacao" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center fixed-bottom pt-2 mb-1" style="background-color: white">
        <div class="container  text-center">
            &copy; 2023 - BTZ Transports
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notificacao.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/toastr.js/toastr.min.js"></script>
@if (TempData["MSG_SUCCESS"] != null)
{
	<script type="text/javascript">
		toastr.success('@TempData["MSG_SUCCESS"]');
	</script>
}
else if (TempData["MSG_ERRO"] != null)
{
	<script type="text/javascript">
		toastr.error('@TempData["MSG_ERRO"]');
	</script>
}